music_path: "/app/music/"

spotify:
  client_id: "46650a3fe727435b89284c4362af8294"
  client_secret: "6871707a1bba4cc397531c268dfbce0c"

musicbrainz:
  root_url: "http://192.168.1.105:5000"
  rate_limit: "none"

qobuz:
  region: "gb-en"

tidal:
  client_id: LCyOOH2KYtx0nF88
  client_secret: AsIV7PFmMWOb1q4m3hCYSOnpYXXOrIOCmV2BEuL3A2c=

lastfm:
  apikey: a30695b94c48d8427a12ff777cfefc52
  sharedsecret: 5a3d96df725dc290826cff852813199b


logging:
  level: "INFO"
  rotation:
    max_bytes: 10485760 # 10MB
    backup_count: 5

