services:
  jamarr_db:
    image: postgres:18.1-alpine
    container_name: jamarr_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:8110:8110"

    env_file:
      - .env
    environment:
      POSTGRES_DB: jamarr
      PGPORT: 8110

    volumes:
      - /mnt/optane-jamarr/jamarr_db:/var/lib/postgresql


  jamarr:
    build: .
    container_name: jamarr
    network_mode: "host"
    depends_on:
      - jamarr_db
    env_file:
      - .env
    volumes:
      - type: volume
        source: music
        target: /app/music
        read_only: true
        volume:
          nocopy: true
      - /mnt/config/q-jamarr/jamarr:/app/cache
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      HOST_IP: ${HOST_IP:-127.0.0.1}
      HOST_PORT: 8111
      DB_HOST: 127.0.0.1
      DB_PORT: 8110
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: jamarr


volumes:
  music:
    driver_opts:
      type: "nfs"
      o: "addr=REDACTED_IP,nolock,soft,rw"
      device: ":/mnt/tank/music/library"
