services:
  jamarr_db:
    image: postgres:18.1-alpine
    container_name: jamarr_db
    network_mode: "host"
    command: postgres -p 8110
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: jamarr
    volumes:
      - /mnt/config/q-docker/jamarr/postgres:/var/lib/postgresql/data


  jamarr:
    build: .
    container_name: jamarr
    network_mode: "host"
    depends_on:
      - jamarr_db
    env_file:
      - .env
    volumes:
      - type: volume
        source: music
        target: /app/music
        read_only: true
        volume:
          nocopy: true
      - /mnt/config/q-docker/jamarr:/app/cache
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - HOST_IP=${HOST_IP:-127.0.0.1}
      - HOST_PORT=8111
      - DB_HOST=127.0.0.1
      - DB_PORT=8110
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=jamarr


volumes:
  music:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.201,nolock,soft,rw"
      device: ":/mnt/tank/music/library"
