ALTER TABLE renderer
    ADD COLUMN IF NOT EXISTS icon_url TEXT,
    ADD COLUMN IF NOT EXISTS icon_mime TEXT,
    ADD COLUMN IF NOT EXISTS icon_width INTEGER,
    ADD COLUMN IF NOT EXISTS icon_height INTEGER;
