ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "user"
ALTER COLUMN is_admin SET DEFAULT FALSE;

ALTER TABLE "user"
ALTER COLUMN is_admin SET NOT NULL;
