name: Android Build

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/android_build.yml"
      - "android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/android_build.yml"
      - "android/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: android
    env:
      GRADLE_USER_HOME: /tmp/gradle-cache

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407

      - name: Install Android SDK packages
        run: sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0" "system-images;android-36;google_apis;x86_64" "emulator"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run Android checks
        uses: reactivecircus/android-emulator-runner@70f4dee990796918b78d040e3278474bdbd348a7
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          profile: pixel_6
          working-directory: android
          script: RUN_ANDROID_INSTRUMENTATION=1 ./test.sh
