name: Lint

permissions:
  contents: read

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/pr_lint.yml"
      - "app/**"
      - "scripts/**"
      - "tests/**"
      - "web/**"
      - "docker-compose.ci.yml"
      - "Dockerfile.node-ci"
      - "lint.sh"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Create dummy .env
        run: |
          cat <<EOF > .env
          POSTGRES_USER=jamarr
          POSTGRES_PASSWORD=jamarr_secret
          DB_USER=jamarr
          DB_PASS=jamarr_secret
          TEST_DB_USER=jamarr_test
          TEST_DB_PASSWORD=jamarr_test_secret
          EOF

      - name: Make scripts executable
        run: chmod +x lint.sh

      - name: Run Lint
        run: ./lint.sh
