name: Test

permissions:
  contents: read

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/pr_test.yml"
      - "app/**"
      - "tests/**"
      - "migrations/**"
      - "config.yaml"
      - "docker-compose.test.yml"
      - "Dockerfile"
      - "pyproject.toml"
      - "test.sh"
      - "uv.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: false

      - name: Create dummy .env
        run: |
          cat <<EOF > .env
          POSTGRES_USER=jamarr
          POSTGRES_PASSWORD=jamarr_secret
          DB_USER=jamarr
          DB_PASS=jamarr_secret
          TEST_DB_USER=jamarr_test
          TEST_DB_PASSWORD=jamarr_test_secret
          LASTFM_API_KEY=dummy_lastfm_key
          LASTFM_SHARED_SECRET=dummy_lastfm_secret
          EOF

      - name: Make scripts executable
        run: chmod +x test.sh

      - name: Run Tests
        run: ./test.sh
